#specifing a default connection to our computer

default:
  adapter: mysql2
  database: musical_api
  username: traci
  password: sinatra
  host: localhost
development:
  adapter: mysql2
  database: musical_api
  username: traci
  password: sinatra
  host: localhost
production:
  adapter: mysql2
  database: musical_api
  username: traci
  password: sinatra
  host: localhost