source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'pry' #this is for testing
gem 'mysql2'
gem 'sinatra-activerecord' #an orm -- like bookshelf, allows us to talk to the server
gem 'bcrypt'

group :development do 
  gem 'mysql2'
end

group :production do 
  gem 'mysql2'
end
